NumPy is the base library for all data science operations. It is fast and performs data processing effectively.

In [1]:
import numpy

**Creating numpy array from a 1-D list**

In [2]:
lst=[9,26,13,1,30,12,44,89,31]
print(lst)
print(type(lst))

[9, 26, 13, 1, 30, 12, 44, 89, 31]
<class 'list'>


In [3]:
arr1=numpy.array(lst)
print(arr1)
print(type(arr1))

[ 9 26 13  1 30 12 44 89 31]
<class 'numpy.ndarray'>


**Create numpy array from 2-D list**

In [4]:
lst2=[
    [12,45,32,56],
    [25,78,81,42],
    [11,78,43,22]
]
print(lst2)

[[12, 45, 32, 56], [25, 78, 81, 42], [11, 78, 43, 22]]


In [5]:
arr2=numpy.array(lst2)
print(arr2)

[[12 45 32 56]
 [25 78 81 42]
 [11 78 43 22]]


**processing a list**

In [6]:
for row in lst2:
  for val in row:
    val+=3
    print(val)

15
48
35
59
28
81
84
45
14
81
46
25


**processing numpy array**

In [7]:
arr2+=3
print(arr2)

[[15 48 35 59]
 [28 81 84 45]
 [14 81 46 25]]


In [9]:
arr2=arr2**2
print(arr2)

[[ 225 2304 1225 3481]
 [ 784 6561 7056 2025]
 [ 196 6561 2116  625]]


**Creating numpy array using 0's and 1's**

In [10]:
z=numpy.zeros((4,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
o=numpy.ones(9)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
narr=numpy.full((3,5),13)
print(narr)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


**creating identity matrix**

In [13]:
iarr=numpy.eye(5)
print(iarr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**create numpy array using arange()**

In [14]:
a1=numpy.arange(1,25)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [15]:
a2=numpy.arange(75,90,2)
print(a2)

[75 77 79 81 83 85 87 89]


In [16]:
a3=numpy.arange(50,25,-3)
print(a3)

[50 47 44 41 38 35 32 29 26]


**creating numpy array using linear spacing**

In [17]:
a4=numpy.linspace(0,1,5)
print(a4)

[0.   0.25 0.5  0.75 1.  ]


In [18]:
a5=numpy.linspace(1,13,9)
print(a5)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]
