**create numpy array with random values**

In [1]:
import numpy

In [3]:
arr1=numpy.random.random(10)
print(arr1)

[0.22404996 0.17852401 0.56034619 0.05658827 0.57152318 0.25739264
 0.41578139 0.14241378 0.93110661 0.14508333]


In [5]:
arr2=numpy.random.random((3,5))
print(arr2)

[[0.49778098 0.33024478 0.4528737  0.92683754 0.18574894]
 [0.70920536 0.94714952 0.29356939 0.78604593 0.53423077]
 [0.86588821 0.27108957 0.8176335  0.60213674 0.33591002]]


In [16]:
arr3=numpy.random.randint(10)
print(arr3)

2


In [18]:
arr4=numpy.random.randint(1,50,10)
print(arr4)

[15 16  9 24 27 44 35 40  6 12]


In [19]:
arr5=numpy.random.randint(1,100,(5,7))
print(arr5)

[[93 46 21 62 93 57 48]
 [10 16 18 67 67  7 47]
 [87 28 43 43 98 99 32]
 [20 29 17 68 53 81 78]
 [56 61 10  1 68 28 29]]


In [20]:
print(arr5.shape)

(5, 7)


**Create a numpy array with lambda function**

In [21]:
f=lambda n:n**2

In [22]:
print(f(13))

169


In [23]:
f=lambda i,j:i+j
print(f(9,13))

22


In [24]:
arr6=numpy.fromfunction(lambda i,j:i+j,(3,3),dtype=int)
print(arr6)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
