In [1]:
import numpy

**basic arithmetic operations**

In [3]:
arr1=numpy.array([1,2,3,4])
arr2=numpy.array([8,6,9,8])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 9  8 12 12]
[-7 -4 -6 -4]
[ 8 12 27 32]
[0.125      0.33333333 0.33333333 0.5       ]


**Scalar operations**

In [5]:
arr3=numpy.array([1,2,3,4,5,6,7])
print(arr3+5)
print(arr3*2)
print(arr3**2)

[ 6  7  8  9 10 11 12]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


**Aggregate functions**

In [12]:
arr4=numpy.array([1,2,3,4,5,6,7,8,9])
print(arr4.sum())
print(arr4.mean())
print(arr4.std())
print(arr4.var())
print(numpy.corrcoef(arr4))
print(arr4.max())
print(arr4.min())

45
5.0
2.581988897471611
6.666666666666667
1.0
9
1


**Element wise functions**

In [14]:
arr5=numpy.array([1,2,3,4,5])
print(numpy.sin(arr5))
print(numpy.cos(arr5))
print(numpy.tan(arr5))
print(numpy.log(arr5))
print(numpy.sqrt(arr5))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]


**rounding and absolute**

In [16]:
arr6=numpy.array([1.4,2.6,-3.7])
print(numpy.round(arr6))
print(numpy.abs(arr6))

[ 1.  3. -4.]
[1.4 2.6 3.7]


**Comparisons**

In [19]:
arr7=numpy.array([1,2,3])
arr8=numpy.array([4,2,5])
print(arr7==arr8)
comp=(arr7==arr8)
print(comp.all())
print(arr7>arr8)

[False  True False]
False
[False False False]


In [21]:
arr9=numpy.array([[12,23],[45,34],[65,49]])
arr10=numpy.array([[11,59],[45,73],[71,49]])
comp=(arr9==arr10)
print(comp.all())
if comp.all():
  print('numpy arrays have same values')
else:
  print('numpy arrays are different')

False
numpy arrays are different


**Cumulative result**

In [23]:
arr11=numpy.array([1,2,3,4,5])
print(numpy.cumsum(arr11))
print(numpy.cumprod(arr11))

[ 1  3  6 10 15]
[  1   2   6  24 120]
