In [1]:
import numpy

In [3]:
a1=numpy.array([1,2,3,4,5])
a2=numpy.array([10,20,30,40,40,60,70])
res=numpy.concatenate((a1,a2))
print(res)

[ 1  2  3  4  5 10 20 30 40 40 60 70]


In [6]:
a3=numpy.array([[1,2,3],[4,5,6]])
a4=numpy.array([[12,23,34],[56,67,78],[89,90,76]])
res=numpy.concatenate((a3,a4))
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [12 23 34]
 [56 67 78]
 [89 90 76]]


In [10]:
a5=numpy.array([[1,2,3],[4,5,6]])
print(a5.shape)
a6=numpy.array([[12,23],[45,56]])
print(a6.shape)

res=numpy.concatenate((a5,a6),axis=1)
print(res)

(2, 3)
(2, 2)
[[ 1  2  3 12 23]
 [ 4  5  6 45 56]]
