In [1]:
import numpy

In [2]:
a1=numpy.array([12,23,34,45,56,67,78,89])
print(a1)

[12 23 34 45 56 67 78 89]


In [3]:
print(a1[0])

12


In [4]:
print(a1[5])

67


In [5]:
print(a1[2:6])

[34 45 56 67]


In [6]:
print(a1[-1])

89


In [7]:
print(a1[::-1])

[89 78 67 56 45 34 23 12]


In [8]:
print(a1[4:])

[56 67 78 89]


In [9]:
print(a1[:5])

[12 23 34 45 56]


In [11]:
lst=[
    [12,23,34,33,77],
    [54,43,32,22,11],
    [21,76,98,76,99]
]
a2=numpy.array(lst)
print(a2)

[[12 23 34 33 77]
 [54 43 32 22 11]
 [21 76 98 76 99]]


In [12]:
print(a2[:,:])

[[12 23 34 33 77]
 [54 43 32 22 11]
 [21 76 98 76 99]]


In [13]:
print(a2[1,3])

22


In [14]:
print(a2[1:,:])

[[54 43 32 22 11]
 [21 76 98 76 99]]


In [15]:
print(a2[1:,1:3])

[[43 32]
 [76 98]]
