In [1]:
import numpy

**Fliter**

In [5]:
a1=numpy.random.randint(1,75,10)
print(a1)

[31 50 14 33 32 52 43 43 69 20]


In [6]:
filtered=a1[a1>50]
print(filtered)

[52 69]


In [7]:
odd=a1[a1%2==1]
print(odd)

[31 33 43 43 69]


**Sort**

In [8]:
a2=numpy.random.randint(25,100,10)
print(a2)

[61 34 32 76 58 49 48 54 46 88]


In [9]:
print(numpy.sort(a2))

[32 34 46 48 49 54 58 61 76 88]


In [10]:
print(numpy.sort(a2)[::-1])

[88 76 61 58 54 49 48 46 34 32]


**Unique**

In [11]:
a3=numpy.array([9,26,1,13,30,45,9,25,1,17,26,15,13])
print(numpy.unique(a3))

[ 1  9 13 15 17 25 26 30 45]


**Split**

In [13]:
a4=numpy.array([9,26,1,13,30,45,9,25,1,17,26,15,13,11,34])
print(numpy.split(a4,5))

[array([ 9, 26,  1]), array([13, 30, 45]), array([ 9, 25,  1]), array([17, 26, 15]), array([13, 11, 34])]


In [16]:
a5=numpy.array([9,26,1,13,30,45,9,25,1,17,26,15])
print(a5.shape)
print(numpy.array_split(a5,5))

(12,)
[array([ 9, 26,  1]), array([13, 30, 45]), array([ 9, 25]), array([ 1, 17]), array([26, 15])]
